### PR TITLE
Acknowledgement to EPFL and CIBM

### PR DESCRIPTION
**Pull request by poldap**
Would close issue #37. 

Just a suggestion on how to do it. Please feel free to suggest changes.

### CODE REVIEW

**Comment by FerreolS** [comment]
Both acknowledgement should also  be put in the [doc pages](https://biomedical-imaging-group.github.io/GlobalBioIm/) by editing the file : Doc/source/index.rst

**Review by FerreolS — CHANGES_REQUESTED** [review]
- reduce file size and possibly find the svg
- use more markdown in README.md
- add link to CIBM
- move it to an acknowledgement section at the end
- same in Doc/source/index.rst for the doc pages

**Comment by poldap** [comment]
About more markdown:
- I can't select the size of the image if I use markdown. That's why I tend to use HTML for that. 
- Markdown tables don't allow a cell that spans more than one column, as far as I know, and that is a nice solution for captions in my opinion

What do you think?

**Comment by poldap** [comment]
Of course, it did not visualize well in my README.md because I was already tweaking the paths to the main repo.

**Comment by poldap** [comment]
I've used .png instead, the best (and smallest) format they give for network distribution.

**Comment by poldap** [comment]
@FerreolS let me know about the markdown stuff and I will proceed with the remaining changes.

**Comment by FerreolS** [comment]
> @FerreolS let me know about the markdown stuff and I will proceed with the remaining changes.

I'm fine if you prefer html.

**Comment by esoubies** [comment]
Hi, thanks to both of you for the adjustments.
Everything is fine for me !

**Comment by esoubies** [comment]
Actually, I'm thinking that we should add ERC too in acknowledgement no ?

**Comment by FerreolS** [comment]
Probably. I think acknowledgement  should be also present in the documentation in Doc/source/index.rst

**Comment by esoubies** [comment]
Hi, I added the ERC logo as well as all these acknowledgements in the documentation page (see below)
Capture du 2022-03-25 10-34-54

**Pull request merged**
