### PR TITLE
Fix l2 prox for schatten (used to be prox of squared l2)

### PR DESCRIPTION
**Pull request by AleixBP**
Would like to thank Thomas Debarre and Emmanuel Soubies for discussion.
Either replace 
    E=E./(1+alpha);
for
         E=max(1-alpha./sqrt(sum(E.^2,3)),0);
         E=bsxfun(@times, E, pE)
or notice that schatten-2 is the Frobenius norm, i.e. no need for svds.

### CODE REVIEW

**Comment by esoubies** [comment]
Thanks Aleix !  Seems fine in 2D but in 3D I think that we should have also  +x(:,:,3).^2+x(:,:,5).^2 in the sqrt for the Frob norm no? (see the Note here https://biomedical-imaging-group.github.io/GlobalBioIm/cost.html#costmixnormschatt1)

**Comment by AleixBP** [comment]
yes, definitely. sorry i forgot it is implemented for both 2d and 3d.

**Comment by esoubies** [comment]
Yes this would indeed be more general, but given how we store the symetric matrices, not sure that we can avoid distinguishing the 2D and 3D cases. Anyway, right now this cost function works only in 2D and 3D, so you can do the simple way of putting an "if" I think.

**Comment by AleixBP** [comment]
As you prefer. The diagonal indices would be given by diag_inds=cumsum(dim+1:-1:2)-dim.
And then
x2=x.^2
Frob=sqrt(2*sum(x2,3) - sum(x2(:,:,diag_inds),3))
Let me know what you think is cleanest and I will write that down.

**Comment by esoubies** [comment]
Let's go for the diags_inds option ;)
Thanks !

**Comment by esoubies** [comment]
Thanks ! Sorry, I just saw something now... The parameter alpha is missing : I think it should be y=max(1-alpha./Frob,0).*x;

**Comment by AleixBP** [comment]
True! Damn, I should have checked all this better. Thanks for the feedback.

**Pull request merged**
